---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
        - name: backend
          image: "public.ecr.aws/l1w4p1o6/project-backend-api"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              httpHeaders:
              - name: Custom-Header
                value: Awesome
            initialDelaySeconds: 60
            periodSeconds: 30
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: DB_HOST
              value: *
            - name: DB_PORT
              value: *
            - name: DB_NAME
              value: *
            - name: DB_USERNAME
              value: *
            - name: DB_PASSWORD
              value: *
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  type: LoadBalancer
  ports:
     - protocol: TCP
       port: 8080
       targetPort: 8080
...