apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend-helm.fullname" . }}
  
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "backend-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "backend-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
          env:
            - name: DB_HOST
              value: {{ .Values.database.DB_HOST }}
            - name: DB_PORT
              value: {{ .Values.database.DB_PORT }}
            - name: DB_NAME
              value: {{ .Values.database.DB_NAME }}
            - name: DB_USERNAME
              value: {{ .Values.database.DB_USERNAME }}
            - name: DB_PASSWORD
              value: {{ .Values.database.DB_PASSWORD }}
        