apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend-helm.fullname" . }}
  annotations:
    prometheus.io/port: "backend"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/part-of: backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: backend
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      
  selector:
    {{- include "backend-helm.selectorLabels" . | nindent 4 }}
