apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend-helm.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      
  selector:
    {{- include "backend-helm.selectorLabels" . | nindent 4 }}
